services:
    # FastAPI 應用服務
    fastapi-app:
        build:
            context: ..
            dockerfile: Dockerfile
            target: development
        container_name: fastapi-dev
        ports:
            - "8000:8000"
        volumes:
            # 掛載源代碼以支援熱重載
            - ..:/app
            # 排除 node_modules 和其他不需要的目錄
            - /app/__pycache__
            - /app/.pytest_cache
        environment:
            - DEBUG=true
            - LOG_LEVEL=DEBUG
            - HOST=0.0.0.0
            - PORT=8000
            - RELOAD=true
        env_file:
            - ../.env
        networks:
            - fastapi-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/stats/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

    # 測試服務
    fastapi-test:
        build:
            context: ..
            dockerfile: Dockerfile
            target: development
        container_name: fastapi-test
        volumes:
            - ..:/app
        environment:
            - PYTHONPATH=/app
        networks:
            - fastapi-network
        profiles:
            - testing
        command:
            [
                "uv",
                "run",
                "pytest",
                "tests/",
                "-v",
                "--cov=src",
                "--cov-report=html",
                "--cov-report=term",
            ]

    # 生產環境服務
    fastapi-prod:
        build:
            context: ..
            dockerfile: Dockerfile
            target: production
        container_name: fastapi-prod
        ports:
            - "8000:8000"
        environment:
            - DEBUG=false
            - LOG_LEVEL=INFO
            - HOST=0.0.0.0
            - PORT=8000
        env_file:
            - ../.env
        networks:
            - fastapi-network
        profiles:
            - production
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/stats/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s

networks:
    fastapi-network:
        driver: bridge

volumes:
    fastapi-data:
