# GitHub Codespaces 專用的 Docker Compose 覆蓋配置

# GitHub Codespaces 專用的 Docker Compose 覆蓋配置
# 使用方式: docker-compose -f ../docker/docker-compose.yml -f docker-compose.codespaces.yml up

version: '3.8'

services:
  fastapi-app:
    # Codespaces 特定配置
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=true
      - ENABLE_AUTO_TEST=true
      - POPULATE_SAMPLE_DATA=true
      - CODESPACES=true
    
    # 端口配置
    ports:
      - "8000:8000"
      - "5678:5678"  # debugpy 端口
    
    # 卷掛載 - Codespaces 優化
    volumes:
      - .:/app:cached
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/fastapi_env
    
    # Codespaces 標籤
    labels:
      - "codespaces.port.8000.visibility=public"
      - "codespaces.port.8000.onAutoForward=openBrowser"
      - "codespaces.port.5678.visibility=private"
    
    # 啟動命令
    command: ["python", "run.py"]
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/stats/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s